# == This file defines the page_layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: intro
  unique: true
  elements:
  - image_teaser
  - intro_text
  - slider
  autogenerate:
  - image_teaser
  - intro_text
  - slider

- name: standard
  elements:
  - text_block
  - content_block
  autogenerate:
  - text_block
  - content_block

- name: content_page
  elements:
  - content_block
  - call_to_action
  - slider
  autogenerate:
  - content_block
  - call_to_action
  - slider

- name: blog
  insert_elements_at: top
  elements:
  - blog_post
  autogenerate:
  - blog_post

- name: category
  elements:
  - category_intro
  - gallery
  autogenerate:
  - category_intro
  - gallery

- name: microsite
  elements:
  - portrait_image
  - slider
  autogenerate:
  - portrait_image
  - slider

- name: external
  redirects_to_external: true

# global pages

- name: footer
  unique: true
  layoutpage: true
  elements:
  - footer_note
  - footer_links
  - social_button
  autogenerate:
  - footer_note
  - footer_links
